### ISSUE TITLE
algorithm description discussion

### ISSUE THREAD

**Issue by ghost** [schatzlab/PodPlot#2]
Thank you @mschatz and this is great. please kindly put down the algorithm for this. I am writing a new visualization library for pacbiohifi using the OpenGLC and would be really happy to include this in the same. I thank you for all the information.

**Comment by mschatz** [comment]
It is pretty straightforward - just sort the read lengths from longest to shortest, and then iterate through to record the cumulative sum of lengths above a given min read length.

Good luck!
Mike

**Comment by ghost** [comment]
@mschatz thank you for the reply and i read the code and i was sure but i want to ask, so asked.

alles super,
gaurav

**Comment by ghost** [comment]
@mschatz i wrote this to the algorithm to sort according to the length. Now will implement a filter according to the length and will incoporate the OpenGLC for the visualization. Kindly let me know. 
```
podplot (){
  awk '/^>/ {printf("\n%s\n",$0);next; } \
            { printf("%s",$0);} END {printf("\n");}' input.fasta > read.fasta

  declare -a sortheader=()
  for i in $(cat read.fasta | awk '/^>/ {print $1}' | sed "s/>//g");
  do 
     sortheader+=("${i}")
  done
  declare -a stringsort=()
  for i in $(cat read.fasta | awk '!/^>/ { print $1 }');
  do 
     stringsort+=("${i}")
  done
  declare -a length=()
  for i in $(cat less.fasta | awk '!/^>/ {print $1 }' | awk '{ print length($1) }'); 
  do 
    length+=("${I}")
  done
}
```
